### PR TITLE
Fix desktop nav bar styling

### LINKED ISSUE #139: Header text Cross-chain missaligned in narrow screen
Screenshot 2023-01-08 at 11 52 03

abbr to x-chain when narrow, or switch to mobile header sooner

### PR DESCRIPTION
**Pull request by vkulinich-cl**
Fixes #139 

Fixed:
- added border gradient to the Pool card
- fixed scroll for the main page
- fixed overlapping of the modal for mobil view
- fixed styling for the disabled button

### CODE REVIEW

File: src/components/Layout/Header/Header.tsx [hunk 1]
```diff
@@ -12,6 +12,7 @@ import { Spinner } from "components/Spinner/Spinner.styled"
 
 export const Header = () => {
   const isDesktop = useMedia(theme.viewport.gte.sm)
```
Comment (obsivac-cleevio) [inline src/components/Layout/Header/Header.tsx:14]: nestacilo by tady jen prepsat na toto?
```suggestion
  const isDesktop = useMedia(theme.viewport.gte.md)
```
jsem z tech media queries trochu zmateny 😄

**Review by obsivac-cleevio — CHANGES_REQUESTED** [review]

File: src/components/Layout/Header/Header.tsx (hunk 1 above)
Comment (vkulinich-cl) [reply src/components/Layout/Header/Header.tsx:14]: prave ze tam jsou 3 stavy:
1. Pro Desktop view
2. Pro Desktop view ale pro mensi obrazovky
3. Pro Mobilni view

**Review by obsivac-cleevio — APPROVED** [review]
